package commons

const (
	PAYMENTSTATUS_UNPAID      = 0
	PAYMENTSTATUS_DOWNPAYMENT = 2
	PAYMENTSTATUS_CANCEL      = 3
	PAYMENTSTATUS_PAID        = 200
)

const (
	ORDERSTATUS_DRAFT      = 1
	ORDERSTATUS_INPROGRESS = 2
	ORDERSTATUS_REJECTED   = 3
	ORDERSTATUS_DONE       = 200
)

const (
	PAYMENTMETHOD_CASH     = "Cash"
	PAYMENTMETHOD_EWALLET  = "E-Wallet"
	PAYMENTMETHOD_TRANSFER = "Transfer"
)
